-- core
require("core.keymaps")
require("core.basic")
-- config
require("config.lazy")
-- plugins
-- require("plugins.lsp")
-- require("plugins.telescope")
-- require("plugins.colorscheme")
-- require("plugins.nvimtree")
-- require("plugins.formatter")
-- require("plugins.autopairs")
-- require("plugins.lualine")
-- require("plugins.comment")
-- require("plugins.gitblame")
-- require("plugins.toggleterm")
-- require("plugins.winbar")
-- require("plugins.nvim-treesitter")
-- require("plugins.bufferline")
-- require("plugins.gps")
-- require("plugins.copilot")
-- require("plugins.doxygen")
