-- core
require("core.keymaps")
require("core.basic")
-- plugins
require("plugins.plugins")
require("plugins.telescope")
require("plugins.colorscheme")
require("plugins.nvimtree")
require("plugins.formatter")
require("plugins.cmp")
require("plugins.mason")
require("plugins.autopairs")
require("plugins.lualine")
require("plugins.comment")
require("plugins.gitblame")
require("plugins.toggleterm")
require("plugins.winbar")
require("plugins.nvim-treesitter")
require("plugins.bufferline")
require("plugins.gps")
